- name: Set up Python environment
  uses: actions/setup-python@v4
  with:
    python-version: 3.11

- name: Install dependencies
  run: |
    cd capstone/capstoneproject
    pip install -r requirements.txt

- name: Run migrations
  run: |
    cd capstone/capstoneproject
    python manage.py migrate --settings=capstoneproject.test_settings

- name: Run tests with pytest
  run: |
    cd capstone/capstoneproject
    pytest --settings=capstoneproject.test_settings

- name: Run flake8
  run: |
    cd capstone/capstoneproject
    flake8 .
