name: CI

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: true
      DJANGO_SETTINGS_MODULE: capstoneproject.test_settings
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/capstoneproject" >> $GITHUB_ENV

    - name: Migrate DB
      run: python manage.py migrate --settings=capstoneproject.test_settings

    - name: Run tests with pytest
      run: pytest

    - name: Lint with flake8
      run: flake8 .
